/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package submarine;

import com.martinnovak.utils.Configuration;
import com.martinnovak.utils.Util;
import java.awt.Font;

/**
 *
 * @author Administrator
 */
public class SubmarineApp extends javax.swing.JFrame {

    static Configuration config;
    static Submarine submarine;

    /**
     * Creates new form SubmarineApp
     */
    public SubmarineApp() {
        initComponents();


        config = new Configuration();

        Util.log.logToTextArea(logTextArea);
        Util.log.logToConsole(true);

        // ============ INIT FONTS ===========================


        Font fontGuifx = FontLoader.getFont("guifx.ttf");
        Font buttonFont = fontGuifx.deriveFont(14f);

        cameraButton11_Rec.setFont(buttonFont);
        cameraButton7_Play.setFont(buttonFont);
        cameraButton1_Left.setFont(buttonFont);
        cameraButton2_Down.setFont(buttonFont);
        cameraButton5_Right.setFont(buttonFont);
        cameraButton8_Ok.setFont(buttonFont);
        cameraButton6_Up.setFont(buttonFont);
        cameraButton16_Power.setFont(buttonFont);
        cameraButton4_Cancel.setFont(buttonFont);

        Font fontKamera = FontLoader.getFont("kameradings.ttf");
        Font buttonFontKamera = fontKamera.deriveFont(13f);

        cameraButton10_Shot.setFont(buttonFontKamera);


        // ============ INIT SUBMARINE =======================

        try {
            submarine = new Submarine(config);

            // Initial settings

            // stop engines and servo to 0 position
            submarine.setEngineSpeed(0, 0);
            submarine.setEngineSpeed(1, 0);
            //  submarine.setEngineSpeed(2, 0);
            //  submarine.setEngineSpeed(3, 0);
            //  submarine.setEngineSpeed(4, 0);

            submarine.setServoPosition(0, 0);
            submarine.setServoPosition(1, 0);

        } catch (PortNotFoundException e) {
            Util.log.write("Port Not Found");
        }
        /*
         * Controller[] ca =
         * ControllerEnvironment.getDefaultEnvironment().getControllers();
         *
         * for (int i = 0; i < ca.length; i++) {
         *
         * // Get the name of the controller Util.log.write(ca[i].getName());
        }
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Status = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SensorsPanel = new javax.swing.JPanel();
        MainTabPanel = new javax.swing.JTabbedPane();
        Control = new javax.swing.JPanel();
        CameraPanel = new javax.swing.JPanel();
        cameraButton12_F = new javax.swing.JButton();
        cameraButton16_Power = new javax.swing.JButton();
        cameraButton13_FPlus = new javax.swing.JButton();
        cameraButton15_ZoomMinus = new javax.swing.JButton();
        cameraButton10_Shot = new javax.swing.JButton();
        cameraButton14_ZoomPlus = new javax.swing.JButton();
        cameraButton11_Rec = new javax.swing.JButton();
        cameraButton7_Play = new javax.swing.JButton();
        cameraButton6_Up = new javax.swing.JButton();
        cameraButton1_Left = new javax.swing.JButton();
        cameraButton5_Right = new javax.swing.JButton();
        cameraButton2_Down = new javax.swing.JButton();
        cameraButton8_Ok = new javax.swing.JButton();
        cameraButton3_Menu = new javax.swing.JButton();
        cameraButton4_Cancel = new javax.swing.JButton();
        PowerPanel = new javax.swing.JPanel();
        PowerButton1 = new javax.swing.JToggleButton();
        PowerButton2 = new javax.swing.JToggleButton();
        PowerButton3 = new javax.swing.JToggleButton();
        PowerButton5 = new javax.swing.JToggleButton();
        PowerButton4 = new javax.swing.JToggleButton();
        PowerButton6 = new javax.swing.JToggleButton();
        PowerButton7 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        MenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Submarine");
        setPreferredSize(new java.awt.Dimension(400, 750));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setPreferredSize(new java.awt.Dimension(412, 26));

        Status.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submarine/resources/accept.png"))); // NOI18N
        Status.setText("OK");
        Status.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/submarine/resources/about.png"))); // NOI18N
        Status.setIconTextGap(6);
        Status.setMaximumSize(new java.awt.Dimension(336, 16));
        Status.setPreferredSize(new java.awt.Dimension(36, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        SensorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sensors"));
        SensorsPanel.setPreferredSize(new java.awt.Dimension(445, 200));

        javax.swing.GroupLayout SensorsPanelLayout = new javax.swing.GroupLayout(SensorsPanel);
        SensorsPanel.setLayout(SensorsPanelLayout);
        SensorsPanelLayout.setHorizontalGroup(
            SensorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );
        SensorsPanelLayout.setVerticalGroup(
            SensorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        jPanel2.add(SensorsPanel);

        MainTabPanel.setPreferredSize(new java.awt.Dimension(412, 300));

        Control.setPreferredSize(new java.awt.Dimension(407, 200));
        Control.setLayout(new javax.swing.BoxLayout(Control, javax.swing.BoxLayout.X_AXIS));

        CameraPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Camera"));
        CameraPanel.setPreferredSize(new java.awt.Dimension(240, 180));

        cameraButton12_F.setText("F");
        cameraButton12_F.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton12_FMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton12_FMouseReleased(evt);
            }
        });

        cameraButton16_Power.setText("q");
        cameraButton16_Power.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton16_PowerMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton16_PowerMouseReleased(evt);
            }
        });

        cameraButton13_FPlus.setText("F+");
        cameraButton13_FPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton13_FPlusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton13_FPlusMouseReleased(evt);
            }
        });

        cameraButton15_ZoomMinus.setText("-Z");
        cameraButton15_ZoomMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton15_ZoomMinusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton15_ZoomMinusMouseReleased(evt);
            }
        });

        cameraButton10_Shot.setText("7");
        cameraButton10_Shot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton10_ShotMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton10_ShotMouseReleased(evt);
            }
        });

        cameraButton14_ZoomPlus.setText("Z+");
        cameraButton14_ZoomPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton14_ZoomPlusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton14_ZoomPlusMouseReleased(evt);
            }
        });

        cameraButton11_Rec.setText("4");
        cameraButton11_Rec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton11_RecMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton11_RecMouseReleased(evt);
            }
        });

        cameraButton7_Play.setText("1");
        cameraButton7_Play.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton7_PlayMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton7_PlayMouseReleased(evt);
            }
        });

        cameraButton6_Up.setText("W");
        cameraButton6_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton6_UpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton6_UpMouseReleased(evt);
            }
        });

        cameraButton1_Left.setText("A");
        cameraButton1_Left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton1_LeftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton1_LeftMouseReleased(evt);
            }
        });

        cameraButton5_Right.setText("D");
        cameraButton5_Right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton5_RightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton5_RightMouseReleased(evt);
            }
        });

        cameraButton2_Down.setText("S");
        cameraButton2_Down.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton2_DownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton2_DownMouseReleased(evt);
            }
        });

        cameraButton8_Ok.setText("z");
        cameraButton8_Ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton8_OkMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton8_OkMouseReleased(evt);
            }
        });

        cameraButton3_Menu.setText("Menu");
        cameraButton3_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton3_MenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton3_MenuMouseReleased(evt);
            }
        });

        cameraButton4_Cancel.setText("x");
        cameraButton4_Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cameraButton4_CancelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cameraButton4_CancelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CameraPanelLayout = new javax.swing.GroupLayout(CameraPanel);
        CameraPanel.setLayout(CameraPanelLayout);
        CameraPanelLayout.setHorizontalGroup(
            CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cameraButton11_Rec)
                    .addGroup(CameraPanelLayout.createSequentialGroup()
                        .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cameraButton3_Menu, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CameraPanelLayout.createSequentialGroup()
                                .addComponent(cameraButton12_F)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cameraButton16_Power))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CameraPanelLayout.createSequentialGroup()
                                .addComponent(cameraButton15_ZoomMinus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cameraButton6_Up)
                                    .addComponent(cameraButton10_Shot))))
                        .addGap(4, 4, 4)
                        .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cameraButton13_FPlus)
                            .addComponent(cameraButton7_Play)
                            .addComponent(cameraButton14_ZoomPlus)
                            .addComponent(cameraButton5_Right)
                            .addComponent(cameraButton4_Cancel)))
                    .addGroup(CameraPanelLayout.createSequentialGroup()
                        .addComponent(cameraButton1_Left)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cameraButton2_Down)
                            .addComponent(cameraButton8_Ok))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        CameraPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cameraButton10_Shot, cameraButton11_Rec, cameraButton12_F, cameraButton13_FPlus, cameraButton14_ZoomPlus, cameraButton15_ZoomMinus, cameraButton16_Power, cameraButton1_Left, cameraButton2_Down, cameraButton3_Menu, cameraButton4_Cancel, cameraButton5_Right, cameraButton6_Up, cameraButton7_Play, cameraButton8_Ok});

        CameraPanelLayout.setVerticalGroup(
            CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CameraPanelLayout.createSequentialGroup()
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cameraButton12_F)
                    .addComponent(cameraButton16_Power)
                    .addComponent(cameraButton13_FPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cameraButton15_ZoomMinus)
                    .addComponent(cameraButton10_Shot)
                    .addComponent(cameraButton14_ZoomPlus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CameraPanelLayout.createSequentialGroup()
                        .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cameraButton11_Rec)
                            .addComponent(cameraButton7_Play))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CameraPanelLayout.createSequentialGroup()
                        .addComponent(cameraButton6_Up)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cameraButton1_Left)
                    .addComponent(cameraButton8_Ok)
                    .addComponent(cameraButton5_Right))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cameraButton2_Down)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CameraPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cameraButton3_Menu)
                    .addComponent(cameraButton4_Cancel))
                .addGap(17, 17, 17))
        );

        CameraPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cameraButton10_Shot, cameraButton11_Rec, cameraButton12_F, cameraButton13_FPlus, cameraButton14_ZoomPlus, cameraButton15_ZoomMinus, cameraButton16_Power, cameraButton1_Left, cameraButton2_Down, cameraButton3_Menu, cameraButton4_Cancel, cameraButton5_Right, cameraButton6_Up, cameraButton7_Play, cameraButton8_Ok});

        Control.add(CameraPanel);

        PowerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Power"));
        PowerPanel.setPreferredSize(new java.awt.Dimension(150, 353));

        PowerButton1.setText("1");
        PowerButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton1ActionPerformed(evt);
            }
        });

        PowerButton2.setText("2");
        PowerButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton2ActionPerformed(evt);
            }
        });

        PowerButton3.setText("3");
        PowerButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton3ActionPerformed(evt);
            }
        });

        PowerButton5.setText("5");
        PowerButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton5ActionPerformed(evt);
            }
        });

        PowerButton4.setText("4");
        PowerButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton4ActionPerformed(evt);
            }
        });

        PowerButton6.setText("6");
        PowerButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton6ActionPerformed(evt);
            }
        });

        PowerButton7.setText("7");
        PowerButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PowerPanelLayout = new javax.swing.GroupLayout(PowerPanel);
        PowerPanel.setLayout(PowerPanelLayout);
        PowerPanelLayout.setHorizontalGroup(
            PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PowerPanelLayout.createSequentialGroup()
                        .addComponent(PowerButton7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PowerPanelLayout.createSequentialGroup()
                        .addGroup(PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PowerPanelLayout.createSequentialGroup()
                                .addComponent(PowerButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PowerButton2))
                            .addGroup(PowerPanelLayout.createSequentialGroup()
                                .addComponent(PowerButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PowerButton4))
                            .addGroup(PowerPanelLayout.createSequentialGroup()
                                .addComponent(PowerButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PowerButton6)))
                        .addContainerGap(91, Short.MAX_VALUE))))
        );
        PowerPanelLayout.setVerticalGroup(
            PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PowerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerButton1)
                    .addComponent(PowerButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerButton3)
                    .addComponent(PowerButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PowerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerButton5)
                    .addComponent(PowerButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PowerButton7)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        Control.add(PowerPanel);

        MainTabPanel.addTab("Control", Control);

        jPanel2.add(MainTabPanel);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        jPanel3.setPreferredSize(new java.awt.Dimension(490, 100));
        jPanel3.setLayout(new java.awt.BorderLayout());

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        jScrollPane1.setViewportView(logTextArea);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        MenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        MenuBar.add(jMenu2);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PowerButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton1ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(1, PowerButton1.isSelected());
    }//GEN-LAST:event_PowerButton1ActionPerformed

    private void PowerButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton6ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(6, PowerButton6.isSelected());
    }//GEN-LAST:event_PowerButton6ActionPerformed

    private void PowerButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton2ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(2, PowerButton2.isSelected());
    }//GEN-LAST:event_PowerButton2ActionPerformed

    private void PowerButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton3ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(3, PowerButton3.isSelected());
    }//GEN-LAST:event_PowerButton3ActionPerformed

    private void PowerButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton4ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(4, PowerButton4.isSelected());
    }//GEN-LAST:event_PowerButton4ActionPerformed

    private void PowerButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton5ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(5, PowerButton5.isSelected());
    }//GEN-LAST:event_PowerButton5ActionPerformed

    private void PowerButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerButton7ActionPerformed
        // TODO add your handling code here:
        submarine.setPowerConfig(7, PowerButton7.isSelected());
    }//GEN-LAST:event_PowerButton7ActionPerformed

    private void cameraButton12_FMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton12_FMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(12);
    }//GEN-LAST:event_cameraButton12_FMousePressed

    private void cameraButton12_FMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton12_FMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton12_FMouseReleased

    private void cameraButton16_PowerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton16_PowerMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(16);
    }//GEN-LAST:event_cameraButton16_PowerMousePressed

    private void cameraButton16_PowerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton16_PowerMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton16_PowerMouseReleased

    private void cameraButton13_FPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton13_FPlusMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(13);
    }//GEN-LAST:event_cameraButton13_FPlusMousePressed

    private void cameraButton13_FPlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton13_FPlusMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton13_FPlusMouseReleased

    private void cameraButton15_ZoomMinusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton15_ZoomMinusMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(15);
    }//GEN-LAST:event_cameraButton15_ZoomMinusMousePressed

    private void cameraButton15_ZoomMinusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton15_ZoomMinusMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton15_ZoomMinusMouseReleased

    private void cameraButton10_ShotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton10_ShotMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(10);
    }//GEN-LAST:event_cameraButton10_ShotMousePressed

    private void cameraButton10_ShotMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton10_ShotMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton10_ShotMouseReleased

    private void cameraButton14_ZoomPlusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton14_ZoomPlusMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(14);
    }//GEN-LAST:event_cameraButton14_ZoomPlusMousePressed

    private void cameraButton14_ZoomPlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton14_ZoomPlusMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton14_ZoomPlusMouseReleased

    private void cameraButton11_RecMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton11_RecMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(11);
    }//GEN-LAST:event_cameraButton11_RecMousePressed

    private void cameraButton11_RecMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton11_RecMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton11_RecMouseReleased

    private void cameraButton7_PlayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton7_PlayMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(7);
    }//GEN-LAST:event_cameraButton7_PlayMousePressed

    private void cameraButton7_PlayMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton7_PlayMouseReleased
        // TODO add your handling code here:submarine.releaseCameraButtons();
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton7_PlayMouseReleased

    private void cameraButton6_UpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton6_UpMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(6);
    }//GEN-LAST:event_cameraButton6_UpMousePressed

    private void cameraButton6_UpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton6_UpMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton6_UpMouseReleased

    private void cameraButton1_LeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton1_LeftMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(1);
    }//GEN-LAST:event_cameraButton1_LeftMousePressed

    private void cameraButton1_LeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton1_LeftMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton1_LeftMouseReleased

    private void cameraButton8_OkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton8_OkMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(8);
    }//GEN-LAST:event_cameraButton8_OkMousePressed

    private void cameraButton8_OkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton8_OkMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton8_OkMouseReleased

    private void cameraButton5_RightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton5_RightMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(5);
    }//GEN-LAST:event_cameraButton5_RightMousePressed

    private void cameraButton5_RightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton5_RightMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton5_RightMouseReleased

    private void cameraButton2_DownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton2_DownMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(2);
    }//GEN-LAST:event_cameraButton2_DownMousePressed

    private void cameraButton2_DownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton2_DownMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton2_DownMouseReleased

    private void cameraButton3_MenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton3_MenuMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(3);
    }//GEN-LAST:event_cameraButton3_MenuMousePressed

    private void cameraButton3_MenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton3_MenuMouseReleased
        // TODO add your handling code here:
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton3_MenuMouseReleased

    private void cameraButton4_CancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton4_CancelMousePressed
        // TODO add your handling code here:
        submarine.pushCameraButton(4);
    }//GEN-LAST:event_cameraButton4_CancelMousePressed

    private void cameraButton4_CancelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cameraButton4_CancelMouseReleased
        // TODO add your handling code here:submarine.releaseCameraButtons();
        submarine.releaseCameraButtons();
    }//GEN-LAST:event_cameraButton4_CancelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubmarineApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubmarineApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubmarineApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubmarineApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SubmarineApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CameraPanel;
    private javax.swing.JPanel Control;
    private javax.swing.JTabbedPane MainTabPanel;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JToggleButton PowerButton1;
    private javax.swing.JToggleButton PowerButton2;
    private javax.swing.JToggleButton PowerButton3;
    private javax.swing.JToggleButton PowerButton4;
    private javax.swing.JToggleButton PowerButton5;
    private javax.swing.JToggleButton PowerButton6;
    private javax.swing.JToggleButton PowerButton7;
    private javax.swing.JPanel PowerPanel;
    private javax.swing.JPanel SensorsPanel;
    private javax.swing.JLabel Status;
    private javax.swing.JButton cameraButton10_Shot;
    private javax.swing.JButton cameraButton11_Rec;
    private javax.swing.JButton cameraButton12_F;
    private javax.swing.JButton cameraButton13_FPlus;
    private javax.swing.JButton cameraButton14_ZoomPlus;
    private javax.swing.JButton cameraButton15_ZoomMinus;
    private javax.swing.JButton cameraButton16_Power;
    private javax.swing.JButton cameraButton1_Left;
    private javax.swing.JButton cameraButton2_Down;
    private javax.swing.JButton cameraButton3_Menu;
    private javax.swing.JButton cameraButton4_Cancel;
    private javax.swing.JButton cameraButton5_Right;
    private javax.swing.JButton cameraButton6_Up;
    private javax.swing.JButton cameraButton7_Play;
    private javax.swing.JButton cameraButton8_Ok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logTextArea;
    // End of variables declaration//GEN-END:variables
}
